version: '3'

services:
  php-web:
    image: abece7777/php-73
    container_name: php-web
    working_dir: /var/www
    ports:
      - 10080:80
    links:
      - mysql
    volumes:
      - "./root:/var/www"
      - "./docker/php-web/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php-web/custom-vhost.conf:/etc/apache2/sites-available/000-default.conf"

  mysql:
    image: library/mysql:5.7
    container_name: mysql
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=test
      - PMA_PASSWORD=test
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions